[tool.poetry]
name = "dvc-gui"
version = "0.1.0"
description = ""
authors = ["Markus Nutz"]

[tool.poetry.dependencies]
python = "^3.7"
PyQt5 = "=5.9.2"
fbs = "^0.8.4"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
